version: "3.8"

services:
  
  # frontend:
  #   build: ./frontend
  #   container_name: moment-interview-debugging-react-frontend
  #   command: sh -c "cd frontend && npm install && npx just start"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #   working_dir: /usr/src
  #   volumes:
  #     - ./:/usr/src/
  #     - /usr/src/frontend/node_modules
  #   ports:
  #     - "3000:3000"

  backend:
    build: ./backend-go
    container_name: moment-interview-debugging-react-backend-go
    command: sh -c "go help"
