version: "3.8"

services:
  
  frontend:
    build: ./frontend
    container_name: moment-interview-debugging-react-frontend
    command: sh -c "cd frontend && npm install && npx just start"
    environment:
      - NODE_ENV=development
      - PORT=3000
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: moment-interview-debugging-react-backend
    command: sh -c "cd backend && npm install && npx just dev"
    environment:
      - NODE_ENV=development
      - PORT=3001
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3001:3001"
